# Generated by Django 3.1.6 on 2021-02-14 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todomodel',
            name='content',
            field=models.TextField(null=True),
        ),
    ]
