# Generated by Django 3.1.6 on 2021-02-14 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_todomodel_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todomodel',
            name='content',
            field=models.TextField(max_length=1000, null=True),
        ),
    ]
